# Generated by Django 2.2.2 on 2019-07-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criptografia', '0002_auto_20190629_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='C:\\Users\\gabriel\\Desktop\\UFOP\\git\\cripweb\\static/media'),
        ),
    ]
