# Generated by Django 2.2.2 on 2019-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criptografia', '0003_auto_20190702_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
