# Generated by Django 2.2.2 on 2019-07-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criptografia', '0004_document_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='password',
        ),
    ]
